### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by b-t-k** [ConcaveTrillion/robert-louis-stevenson_david-balfour#1]
You need to:
- run typogrify
- run clean
- se build-toc

### content.opf
- description : italics around Kidnapped
- long desc typo: imprisionments
- long description: the colon after "navigate, to his own peril:" is unnecessary. It should just be a comma and all following semicolons turned to commas as well.
- My understanding is alternate titles are done like:
> ```<dc:title id="title-alternate">The Life of King Henry the Fifth</dc:title>```
> ```<meta property="title-type" refines="#title-alternate">alternate</meta>```
- no need to list three source texts or three sets of scans unless you actually used all three which seems unlikely. If you did then there should be something about that in the production notes.
- the wikipedia url should be: `https://en.wikipedia.org/wiki/Catriona_(novel)`

There appears to be quite a few errors of commas being outside punctuation. Not surprising given all the elisions. I've marked the ones I found but you should probably give it a once over as well to make sure we caught them all.

### chapter 9
- datetime's are not strictly necessary outside of letters and this one is really not necessary: `<time datetime="09-16">September the sixteen</time>`

### chapter 15
-  comma should be inside quote: man! ‘Deil hae me’, quo’ 

### chapter 16
- line 26 comma should be inside quote: : fowl,’

### chapter 18
- comma should be inside quote:  ‘Fair gude e’en and fair gude day’,
- comma should be inside quote: “`<span epub:type="se:name.music.song">The House of Airlie</span>`”, and began thus:

### chapter 19
- comma should be inside quote: time of the night.’ —‘Lady’, she said,
- comma should be inside quote: Alpin.’ —‘My dear’, I replied, ‘I 

### Chapter 26
- line 34 you took out a period  before an ellipsis . You should put it back in as the next phrase is a sentence starting with a capital

**Comment by ConcaveTrillion** [comment]
Sorry about all the issues! 

- did clean/typo/build toc. 
- added <i> tags around Kidnapped in description
- fixed long description issues 
- changed title-short to title-alternate
- removed additional PG / archive scans
- fixed wiki url
- removed <time> outside of letter semantics
- fixed commas inside quotes. Also chapter 16 the Bible quote was originally rendered as italics, and per style manual should be double quote as it's not inside dialog, so I fixed that too.
- put the period back before the ellipsis
- did a final clean/typo/build toc/lint

**Comment by b-t-k** [comment]
Apparently, for some reason unknown to me at this point, epubcheck doesn't allow any html in the description so you will have to take the italics back out. Sorry about that.
